### ISSUE TITLE
FR: requireInteraction not supported

### ISSUE THREAD

**Issue by neckarpixel** [asmsuechan/jquery_push_notification#3]
Hey,
it would nice to enable requireInteraction, so that the notification will be displayed until user click on it.

**Comment by asmsuechan** [comment]
Hi, @dhe. Sorry for the late reply. You can set an option for requireInteraction.

```js
$.notify("set requireInteraction option", { requireInteraction: true })
```

https://developer.mozilla.org/en-US/docs/Web/API/notification/requireInteraction
